//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNet.Identity.EntityFramework;

namespace KYHBPA.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class AspNetRole : IdentityRole<Guid, AspNetUserRole>
    {
        private readonly ICollection<AspNetUserRole> _users;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetRole()
        {
            this._users = new HashSet<AspNetUserRole>();
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage",
            "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public override ICollection<AspNetUserRole> Users
        {
            get { return _users; }
        }
    }
}
