//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYHBPA.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int Id { get; set; }
        public byte[] Content { get; set; }
        public string PhotoName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Event_Id { get; set; }
        public Nullable<int> Uploader_Id { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Member Member { get; set; }
    }
}
