//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYHBPA.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PollQuestion()
        {
            this.PollResponses = new HashSet<PollResponse>();
        }
    
        public int Id { get; set; }
        public string Message { get; set; }
        public Nullable<int> Poll_Id { get; set; }
    
        public virtual Poll Poll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PollResponse> PollResponses { get; set; }
    }
}
