//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYHBPA.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public int Id { get; set; }
    }
}
